Company.Web/Controllers/DepartmentController.cs
using Company.Data.Entities;
using Company.Repositiry.Interfaces;
using Company.Services.Interfaces;
using Company.Services.Interfaces.Departement.Dto;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.Web.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var departments = _departmentService.GetAll();

            //TempData.Keep("TextTempMessage");
            return View(departments);
        }
        [HttpGet]
         public IActionResult Create()
         {
            return View();
         }

        [HttpPost]
        public IActionResult Create(DepartmentDto department)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _departmentService.Add(department);

                    TempData["TextTempMessage"] = "Hello from employee index (TempData)";

                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("DepartmentError", "ValidationErrors");

                return View(department);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError("DepartmentError", ex.Message);
                return View(department);
            }
        }

        public IActionResult Details(int? id, string viewName = "Details")
        {
            var department = _departmentService.GetById(id);

            if (department is null)
                return RedirectToAction("NotFoundPage", null, "Home");

            return View(viewName, department);
        }
        [HttpGet]
        public IActionResult Update(int? id)
        {
            return Details(id, "Update");
        }
        [HttpPost]
        public IActionResult Update(int? id, DepartmentDto department)
        {
            if(department.Id != id.Value)
                return RedirectToAction("NotFoundPage", null, "Home");

            _departmentService.Update(department);

            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var department = _departmentService.GetById(id);

            if (department is null)
                return RedirectToAction("NotFoundPage", null, "Home");

            _departmentService.Delete(department);

            return RedirectToAction("Index");
        }
    }
}

Company.Web/Controllers/EmployeeController.cs
using Company.Data.Entities;
using Company.Services.Interfaces;
using Company.Services.Interfaces.Employee.Dto;
using Company.Services.Services;
using Company.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.Web.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IDepartmentService _departmentService;

        public EmployeeController(IEmployeeService employeeService, IDepartmentService departmentService)
        {
            _employeeService = employeeService;
            _departmentService = departmentService;
        }
        
        public IActionResult Index(string searchInp)
        {
            //ViewBag.Message = "Hello from employee index (ViewBag)";

            //ViewData["TextMessage"] = "Hello from employee index (ViewData)";

            //TempData["TextTempMessage"] = "Hello from employee index (TempData)";

            IEnumerable<EmployeeDto> employees = new List<EmployeeDto>();

            if (string.IsNullOrEmpty(searchInp))
            {
                employees = _employeeService.GetAll();
            }
            else
            {
                employees = _employeeService.GetEmployeeByName(searchInp);
            }
            return View(employees);

        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Departments = _departmentService.GetAll();

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(EmployeeDto employee)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _employeeService.Add(employee);

                    return RedirectToAction(nameof(Index));
                }

                return View(employee);
            }
            catch (Exception ex)
            {
                return View(employee);
            }

            //public IActionResult Details(int? id, string viewName = "Details")
            //{

            //}

            //[HttpGet]
            //public IActionResult Update(int id)
            //{

            //}

            //public IActionResult Delete(int id)
            //{

            //}
        }
    }
}

Company.Web/Controllers/RoleController.cs
using Company.Data.Entities;
using Company.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ILogger<RoleController> _logger;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, 
            ILogger<RoleController> logger,
            UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _logger = logger;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.ToListAsync();
            return View(roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel roleModel)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole
                {
                    Name = roleModel.Name
                };

                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded) 
                    return RedirectToAction("Index");

                foreach (var item in result.Errors)
                    _logger.LogError(item.Description);
            }
            return View(roleModel);
        }

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role is null)
                return NotFound();

            var roleViewModel = new RoleViewModel
            {
                Name = role.Name,
                Id = role.Id
            };
            return View(viewName, roleViewModel); 
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            return await Details(id, "Update");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, RoleViewModel roleModel)
        {
            if (id != roleModel.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
                try
                {
                    var role = await _roleManager.FindByIdAsync(id);

                    if (role is null)
                        return NotFound();

                    role.Name = roleModel.Name;
                    role.NormalizedName = roleModel.Name.ToUpper();

                    var result = await _roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                    {
                        _logger.LogInformation("Role Updated Successfully");
                        return RedirectToAction("Index");
                    }

                    foreach (var item in result.Errors)
                        _logger.LogError(item.Description);
                }
                catch (Exception ex)
                {

                    _logger.LogError(ex.Message);
                }
            }

            return View(roleModel);
        }

        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var role = await _roleManager.FindByIdAsync(id);

                if (role is null)
                    return NotFound();

                var result = await _roleManager.DeleteAsync(role);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var item in result.Errors)
                    _logger.LogError(item.Description);
            }
            catch (Exception ex)
            {

                _logger.LogError(ex.Message);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role is null)
                return NotFound();

            ViewBag.RoleId = roleId;

            var users = await _userManager.Users.ToListAsync();

            var usersInRole = new List<UserInRoleViewModel>();

            foreach(var user in users)
            {
                var userInRole = new UserInRoleViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                    userInRole.IsSelected = true;
                else
                    userInRole.IsSelected = false;

                usersInRole.Add(userInRole);
            }

            return View(usersInRole);
        }

        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);

                    if(appUser is not null)
                    {
                        if(user.IsSelected && !await _userManager.IsInRoleAsync(appUser, role.Name))
                            await _userManager.AddToRoleAsync(appUser, role.Name);

                        else if(!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                    }
                }

                return RedirectToAction("Update", new {id = roleId});
            }
            return View(users);
        }
    }
}

Company.Web/Controllers/UserController.cs
using Company.Data.Entities;
using Company.Services.Interfaces.Departement.Dto;
using Company.Web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger _logger;

        public UserController(UserManager<ApplicationUser> userManager, ILogger<UserController> logger)
		{
			_userManager = userManager;
            _logger = logger;
        }
		public async Task<IActionResult> Index(string SearchInp)
		{
			List<ApplicationUser> users;

			if (String.IsNullOrWhiteSpace(SearchInp))
				users = await _userManager.Users.ToListAsync();
			else
				users = await _userManager.Users
					.Where(user => user.NormalizedEmail.Trim().Contains(SearchInp.Trim().ToUpper()))
					.ToListAsync();

			return View(users);
		}

        public async Task<IActionResult> Details(string id, string viewName = "Details")
        {
			var user = await _userManager.FindByIdAsync(id);

            if (user is null)
                return NotFound();

            if(viewName == "Update")
            {
                var userViewModel = new UserUpdateViewModel
                {
                    UserName = user.UserName,
                    Id = user.Id
                };
                return View(viewName, userViewModel);
            }

            return View(viewName, user);
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            return await Details(id, "Update");
        }

        [HttpPost]
        public async Task<IActionResult> Update(string id, UserUpdateViewModel applicationUser)
        {
            if (id != applicationUser.Id)
                return NotFound();

            if (ModelState.IsValid)
            {
				try
				{
                    var user = await _userManager.FindByIdAsync(id);

                    if (user is null)
                        return NotFound();

                    user.UserName = applicationUser.UserName;
                    user.NormalizedUserName= applicationUser.UserName.ToUpper();

                    var result = await _userManager.UpdateAsync(user);

                    if (result.Succeeded)
                    {
                        _logger.LogInformation("User Updated Successfully");
                        return RedirectToAction("Index");
                    }

                    foreach (var item in result.Errors)
                        _logger.LogError(item.Description);
                }
				catch (Exception ex)
				{

                    _logger.LogError(ex.Message);
                }
            }

            return View(applicationUser);
        }

        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);

                if (user is null)
                    return NotFound();

                var result = await _userManager.DeleteAsync(user);

                //user.IsDeleted = true;
                //var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                    return RedirectToAction("Index");

                foreach (var item in result.Errors)
                    _logger.LogError(item.Description);
            }
            catch (Exception ex)
            {

                _logger.LogError(ex.Message);
            }

            return RedirectToAction("Index");
        }
    }
}

Company.Web/Views/Shared/_ActionButtonspartialView.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i> Details
    </a>
</td>
<td>
    <a asp-action="Update" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-edit"></i> Update
    </a>
</td>
<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-trash"></i> Delete
    </a>
</td>

Company.Web/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V4</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<link rel="icon" type="image/png" href="images/icons/favicon.ico"/>

	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

	<link rel="stylesheet" type="text/css" href="~/fonts/font-awesome-4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" type="text/css" href="~/fonts/iconic/css/material-design-iconic-font.min.css">

	<link rel="stylesheet" type="text/css" href="~/animate/animate.css">

	<link rel="stylesheet" type="text/css" href="~/css-hamburgers/hamburgers.min.css">

	<link rel="stylesheet" type="text/css" href="~/animsition/css/animsition.min.css">

	<link rel="stylesheet" type="text/css" href="~/select2/select2.min.css">
	
	<link rel="stylesheet" type="text/css" href="~/daterangepicker/daterangepicker.css">

	<link rel="stylesheet" type="text/css" href="~/css/util.css">
	<link rel="stylesheet" type="text/css" href="~/css/main.css">

</head>
<body>
	
	<div class="limiter">
		<div class="container-login100" style="background-image: url('~/layout-images/bg-01.jpg');">
			<div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
				@RenderBody()
			</div>
		</div>
	</div>
	

	<div id="dropDownSelect1"></div>
	

	<script src="~/js/jquery-3.2.1.min.js"></script>

	<script src="~/animsition/js/animsition.min.js"></script>

	<script src="~/js/popper.js"></script>
	<script src="~/js/bootstrap.min.js"></script>

	<script src="~/select2/select2.min.js"></script>

	<script src="~/daterangepicker/moment.min.js"></script>
	<script src="~/daterangepicker/daterangepicker.js"></script>

	<script src="~/countdowntime/countdowntime.js"></script>

	<script src="~/js/main.js"></script>

</body>
</html>

Company.Web/Views/Shared/_Layout.cshtml
@inject SignInManager<ApplicationUser> signInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        @if(signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                            </li>
                        }
                        @if (signInManager.IsSignedIn(User))
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark btn btn-primary" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>